# Generated by Django 3.1.2 on 2020-10-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='type',
            new_name='kind',
        ),
    ]
