# Generated by Django 3.1.2 on 2020-10-16 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20201015_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
