# Generated by Django 3.1.2 on 2020-10-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20201016_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
