# Generated by Django 3.1.2 on 2020-10-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20201016_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
    ]
