# Generated by Django 3.1.2 on 2020-10-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_number',
            field=models.CharField(max_length=100),
        ),
    ]
