# Generated by Django 3.1.2 on 2020-10-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_auto_20201017_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
